### ISSUE TITLE
Updated Directory sturcture worklow

### ISSUE THREAD

**Issue by yashksaini-coder** [yogesh0509/web3-DREAM11#20]
Hi, @yogesh0509 , I saw your project can really use some UI/UX features. starting with the navbar animations. I have recently started Nextjs. I would like to work on it. I want to contribute to the Front-End aspect of your project. By giving the navbar better CSS animations.

![image](https://github.com/user-attachments/assets/4327fa55-202b-4fc9-b780-34679840384a)

- [X] I have searched the existing issues.

**Feature Description**  
- Adding CSS animation to make the Front-End look more interactive and makes UI/UX better for the end-users.
- Color transitions: Changing the background or text color on hover.
- Scale animations: Enlarging or shrinking elements slightly when hovered.
- Underline effects: Adding or animating an underline on hover.
- Sliding effects: Elements or borders sliding in when hovered.

**Use Case**  
- Having small light weight animations will make the UI more interactive and make it more engaging with the users.

**Benefits**
- Adding a hover animation to the navbar improves user experience by providing visual feedback, making the interface more interactive, responsive, and intuitive.

**Priority**  
- Medium  Level 2

**Record**  
- [X] I agree to follow this project's Code of Conduct (Required)  
- [X] I'm a GSSOC contributor  
- [X] I want to work on this issue  
- [X] I'm willing to provide further clarification or assistance if needed.

---

Can you assign this issue to me @yogesh0509  as part of the Wob'24 contributor.

**Comment by yogesh0509** [comment]
Hello @yashksaini-coder , currently we are planning on a complete revamp for the front-end of this project with better designs and components. Can you take a look at the design pages [here](https://github.com/yogesh0509/web3-DREAM11/issues/11). 

If there are any improvements, please share them with me. Otherwise I will break that issue into smaller parts and assign some to you.

**Comment by yashksaini-coder** [comment]
well if that's what you are planning @yogesh0509, this issue is no longer required.

Therefore I have a suggestion to convert this into a new issue. 
How about adding an updated directory structure workflow, that sounds good right. 

The best use case is that as new contributors reads the documentation they can understand the project structure giving them an improvement very easily.

I will rename this issue. can you assign this issue to me and add lables of `wob'24` and `level`

**Comment by yogesh0509** [comment]
Hey @yashksaini-coder, we already have a contributing guideline for users to follow. Instead would you be willing to work on newer components with wagmi integration for the frontend. Feel free to give your inputs on any other improvement that you would like to work on?

**Comment by yashksaini-coder** [comment]
> Hey @yashksaini-coder, we already have a contributing guideline for users to follow. Instead would you be willing to work on newer components with wagmi integration for the frontend. Feel free to give your inputs on any other improvement that you would like to work on?

@yogesh0509 well I just started with web3 & blockchain, so wagmi integration is something I haven't touched that. 

Well I understand the fault is mine as I lack knowledge. I am closing this issue. But will contribute in other aspects as a beginner

Make sure to assign the issues up to time. 
Thx for giving me a chance

**Comment by Devamani11D** [comment]
@yashksaini-coder hey
can you help me with the local setup of project on laptop?

**Comment by yogesh0509** [comment]
> @yashksaini-coder hey
> can you help me with the local setup of project on laptop?

Follow the steps [here](https://github.com/yogesh0509/web3-DREAM11/blob/main/server/README.md) and you should be good to go. Let me know if you face any specific issues or error?
